### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by sari777** [phrutis/LostWallets#1]
how to know that the wallet hashes are real one.? it can be fake.
99% wallet dat files are fake. even they are from owners.

**Comment by phrutis** [comment]
There are many ways to check.
Such as checking ckey, mkey with the database.
Reduce the timing of creating an address in the wallet and in the blockchain.
If the timing for creating an address in a wallet points to 2022, and the coins appeared in 2014, such a wallet is clearly fake. 
They haven't figured out how to fake timing yet.
There are other complex ways to check files, people who have been doing this for more than one year know about them.

**Comment by phrutis** [comment]
Verification is a labor-intensive and time-consuming process. There are a lot of nuances. For example, the address could be imported and more. There is no complete certainty where is fake and where is real. There are very high quality fakes. You can check this only when you enter the found password.

**Comment by sari777** [comment]
> Verification is a labor-intensive and time-consuming process. There are a lot of nuances. For example, the address could be imported and more. There is no complete certainty where is fake and where is real. There are very high quality fakes. You can check this only when you enter the found password.

yes that is i am saying.

**Comment by sari777** [comment]
Thanks for guide.
