### ISSUE TITLE
HC error

### ISSUE THREAD

**Issue by gery89** [phrutis/LostWallets#3]
I have a 6900xt with 3900x.
This is the log

Everything is Ok

Folders: 44
Files: 2276
Size:       225959913
Compressed: 8652614
Downloading: [========================================================================================================]
Client is up-to-date!
Got cracker binary type hashcat
Benchmark task...
Server accepted benchmark!
Start chunk...
HC error: hipDeviceGetAttribute(): 1
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
Sending keepalive progress to avoid timeout...
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_FanSpeed_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_Temperature_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
Error from server on solve: {'action': 'sendProgress', 'response': 'ERROR', 'message': 'Agent is marked inactive!'}
CORRECTO: el proceso con PID 16208 (proceso secundario de PID 15816)
ha sido terminado.
CORRECTO: el proceso con PID 15816 (proceso secundario de PID 14500)
ha sido terminado.
finished chunk
Client is up-to-date!
No task available!
No task available!

**Comment by phrutis** [comment]
Report the number of the agent in the group.

**Comment by gery89** [comment]
573

**Comment by gery89** [comment]
Finally i solved the problem.

I used a clean windows 10, and run python hashtopolis. 

To resolve the problem, I had to download de latest version of hashcat and put the folders manually inside of crack folder and runs ok.
